//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rawaa.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rawaa.Resources.Languages.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Request.
        /// </summary>
        public static string CartContinueRoRequest {
            get {
                return ResourceManager.GetString("CartContinueRoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery fee.
        /// </summary>
        public static string CartDeliveryFee {
            get {
                return ResourceManager.GetString("CartDeliveryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is Empty.
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order notes.
        /// </summary>
        public static string CartOrderNotes {
            get {
                return ResourceManager.GetString("CartOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order value.
        /// </summary>
        public static string CartOrderValue {
            get {
                return ResourceManager.GetString("CartOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Summary.
        /// </summary>
        public static string CartPaymentSummary {
            get {
                return ResourceManager.GetString("CartPaymentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the size: .
        /// </summary>
        public static string CartSize {
            get {
                return ResourceManager.GetString("CartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string CartTitlePage {
            get {
                return ResourceManager.GetString("CartTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total summation.
        /// </summary>
        public static string CartTotalSummation {
            get {
                return ResourceManager.GetString("CartTotalSummation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your comment.
        /// </summary>
        public static string CartWriteYourComment {
            get {
                return ResourceManager.GetString("CartWriteYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional information.
        /// </summary>
        public static string DAAdditionalInformation {
            get {
                return ResourceManager.GetString("DAAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment number.
        /// </summary>
        public static string DAApartmentNumber {
            get {
                return ResourceManager.GetString("DAApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building/Villa No.
        /// </summary>
        public static string DABuildingNumber {
            get {
                return ResourceManager.GetString("DABuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Center/Region.
        /// </summary>
        public static string DACityCenterRegion {
            get {
                return ResourceManager.GetString("DACityCenterRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string DACreate {
            get {
                return ResourceManager.GetString("DACreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DADeliveryAddressTitle {
            get {
                return ResourceManager.GetString("DADeliveryAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string DAGovernorate {
            get {
                return ResourceManager.GetString("DAGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name for title.
        /// </summary>
        public static string DAShortNameTitle {
            get {
                return ResourceManager.GetString("DAShortNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string DAStreetName {
            get {
                return ResourceManager.GetString("DAStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn number.
        /// </summary>
        public static string DATurnNumber {
            get {
                return ResourceManager.GetString("DATurnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed fawzy.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string GlobalCalories {
            get {
                return ResourceManager.GetString("GlobalCalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  EGP.
        /// </summary>
        public static string GlobalCurrency {
            get {
                return ResourceManager.GetString("GlobalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string GlobalDelete {
            get {
                return ResourceManager.GetString("GlobalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LanguagePage_Ok {
            get {
                return ResourceManager.GetString("LanguagePage_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current language is English.
        /// </summary>
        public static string LanguagePage_TheSameLange {
            get {
                return ResourceManager.GetString("LanguagePage_TheSameLange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginPage_BtnLongin {
            get {
                return ResourceManager.GetString("loginPage_BtnLongin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string loginPage_doNothave_acount {
            get {
                return ResourceManager.GetString("loginPage_doNothave_acount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string loginPage_email {
            get {
                return ResourceManager.GetString("loginPage_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string loginPage_forgetPass {
            get {
                return ResourceManager.GetString("loginPage_forgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passeord.
        /// </summary>
        public static string loginPage_password {
            get {
                return ResourceManager.GetString("loginPage_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string loginPage_regesterNow {
            get {
                return ResourceManager.GetString("loginPage_regesterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longin.
        /// </summary>
        public static string loginPage_title {
            get {
                return ResourceManager.GetString("loginPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainPage_SearchPlaceHolder {
            get {
                return ResourceManager.GetString("MainPage_SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling order.
        /// </summary>
        public static string ODCancellingOrder {
            get {
                return ResourceManager.GetString("ODCancellingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash for delivery.
        /// </summary>
        public static string ODCashdelivery {
            get {
                return ResourceManager.GetString("ODCashdelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery fee.
        /// </summary>
        public static string ODDeliveryFee {
            get {
                return ResourceManager.GetString("ODDeliveryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery to.
        /// </summary>
        public static string ODDeliveryTo {
            get {
                return ResourceManager.GetString("ODDeliveryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution of the request.
        /// </summary>
        public static string ODExecutionRequest {
            get {
                return ResourceManager.GetString("ODExecutionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice details.
        /// </summary>
        public static string ODInvoiceDetails {
            get {
                return ResourceManager.GetString("ODInvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals on demand.
        /// </summary>
        public static string ODMealsInOrder {
            get {
                return ResourceManager.GetString("ODMealsInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order has been delivered.
        /// </summary>
        public static string ODOrderDelivered {
            get {
                return ResourceManager.GetString("ODOrderDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is now being prepared.
        /// </summary>
        public static string ODOrderPrepared {
            get {
                return ResourceManager.GetString("ODOrderPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order value.
        /// </summary>
        public static string ODOrderValue {
            get {
                return ResourceManager.GetString("ODOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string ODPaymentMethod {
            get {
                return ResourceManager.GetString("ODPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the request has been canceled.
        /// </summary>
        public static string ODRequestCanceled {
            get {
                return ResourceManager.GetString("ODRequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total bill.
        /// </summary>
        public static string ODTotalPrice {
            get {
                return ResourceManager.GetString("ODTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acount.
        /// </summary>
        public static string Shell_Title_Acount {
            get {
                return ResourceManager.GetString("Shell_Title_Acount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Shell_Title_Favorite {
            get {
                return ResourceManager.GetString("Shell_Title_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shell_Title_Home {
            get {
                return ResourceManager.GetString("Shell_Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Shell_Title_Menu {
            get {
                return ResourceManager.GetString("Shell_Title_Menu", resourceCulture);
            }
        }
    }
}
